workflows:
  android-release:
    name: Build Android Release
    environment:
      flutter: stable

    scripts:
      - name: Clean previous build and cache
        script: |
          flutter clean
          flutter pub cache repair

      - name: Get dependencies
        script: flutter pub get

      - name: Build single-architecture APK with obfuscation
        script: >
          flutter build apk
          --release
          --obfuscate
          --split-debug-info=build/symbols

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/symbols/**

