workflows:
  default-workflow:
    name: Default Workflow
    environment:
      flutter: stable
    triggering:
      events:
        - push
        - pull_request
    scripts:
      # Install Dart/Flutter dependencies
      - name: Get dependencies
        script: |
          flutter pub get

      # Build Android APK
      - name: Build Android APK
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
