workflows:
  android-release:
    name: Build Android Release
    environment:
      flutter: stable

    scripts:
      - name: Get dependencies
        script: flutter pub get

      - name: Patch flutter_image_compress for AGP 8
        script: |
          PLUGIN_DIR="$HOME/.pub-cache/hosted/pub.dev/flutter_image_compress-1.1.0/android"
          GRADLE_FILE="$PLUGIN_DIR/build.gradle"

          echo "Adding namespace to flutter_image_compress…"
          if ! grep -q '^ *namespace ' "$GRADLE_FILE"; then
            awk '/^android {/ { print; print "    namespace \"com.flutter.image_compress\""; next } 1' "$GRADLE_FILE" > "$GRADLE_FILE.tmp" && mv "$GRADLE_FILE.tmp" "$GRADLE_FILE"
          else
            echo "Namespace already present."
          fi

      - name: Patch flutter_image_compress Kotlin version to use project kotlin_version
        script: |
          GRADLE_FILE="$HOME/.pub-cache/hosted/pub.dev/flutter_image_compress-1.1.0/android/build.gradle"
          echo "Patching flutter_image_compress Kotlin version..."
          awk '{gsub(/org.jetbrains.kotlin:kotlin-gradle-plugin:[0-9.]+/, "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"); print}' "$GRADLE_FILE" > "$GRADLE_FILE.tmp" && mv "$GRADLE_FILE.tmp" "$GRADLE_FILE"

      - name: Force Kotlin version compatibility
        script: echo "kotlin.version=1.9.24" >> android/gradle.properties

      - name: Build release APK
        script: flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

